# Generated by Django 5.0.8 on 2024-09-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
