# Generated by Django 5.0.8 on 2024-09-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='main_image',
        ),
    ]
