# Generated by Django 5.0.8 on 2024-09-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-images/'),
        ),
    ]
